/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import escolast_bdd_4to.bdd_escolast.Cconexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adrian Carrion
 */
public class interfaz extends javax.swing.JFrame {

    private void limpiar() {
        txtId.setText(null);
        txtCedula.setText(null);
        txtApellido.setText(null);
        txtNombre.setText(null);
        txtDireccion.setText(null);
        txtEmail.setText(null);
        txtFecha.setText(null);
        txtDiscapacidad.setText(null);
        txtObersevaciones.setText(null);
        cbxSexo.setSelectedIndex(0);
        
        
        
        
        
    }

    public interfaz() {
        initComponents();
        setLocationRelativeTo(null);
        cargartabla();
        
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_encabezado1 = new javax.swing.JLabel();
        panel_btn = new javax.swing.JPanel();
        btn1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        btn2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Menu = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btn_BUSCAR = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        cbxSexo = new javax.swing.JComboBox<>();
        txtFecha = new javax.swing.JTextField();
        txtDiscapacidad = new javax.swing.JTextField();
        txtObersevaciones = new javax.swing.JTextField();
        btn_LIMPIAR = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btn__ELIMINAR = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_MODIFICAR = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_GUARDAR = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jlb_relleno3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlumno = new javax.swing.JTable();
        btn_ELIMINAR2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlb_relleno1 = new javax.swing.JLabel();
        jlb_relleno2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tienda");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlb_encabezado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ENCABEZADO1.jpeg"))); // NOI18N
        getContentPane().add(jlb_encabezado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1130, 160));

        panel_btn.setBackground(new java.awt.Color(35, 63, 111));
        panel_btn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn1.setBackground(new java.awt.Color(35, 63, 111));
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn1MouseMoved(evt);
            }
        });
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn1MouseExited(evt);
            }
        });
        btn1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono1.png"))); // NOI18N
        btn1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 50, 50));

        jComboBox1.setBackground(new java.awt.Color(25, 55, 113));
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingresar / Buscar", "Vizualizar" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        btn1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 130, 20));

        jLabel21.setBackground(new java.awt.Color(35, 63, 111));
        jLabel21.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("ALUMNOS");
        btn1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 180, 90));

        panel_btn.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 90));

        btn2.setBackground(new java.awt.Color(35, 63, 111));
        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn2MouseMoved(evt);
            }
        });
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn2MouseExited(evt);
            }
        });
        btn2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono2.png"))); // NOI18N
        btn2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 50, 50));

        jLabel14.setBackground(new java.awt.Color(35, 63, 111));
        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("VISUALIZAR");
        btn2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 180, 90));

        panel_btn.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, 90));

        btn3.setBackground(new java.awt.Color(35, 63, 111));
        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn3MouseMoved(evt);
            }
        });
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn3MouseExited(evt);
            }
        });
        btn3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono4.png"))); // NOI18N
        btn3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 50, 50));

        jLabel16.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("SALIR");
        btn3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 180, 90));

        panel_btn.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 290, 90));

        getContentPane().add(panel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 290, 510));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_BUSCAR.setBackground(new java.awt.Color(35, 63, 111));
        btn_BUSCAR.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_BUSCARMouseMoved(evt);
            }
        });
        btn_BUSCAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BUSCARMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_BUSCARMouseExited(evt);
            }
        });
        btn_BUSCAR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lupa.png"))); // NOI18N
        btn_BUSCAR.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        jPanel2.add(btn_BUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 105, 40, 30));

        txtId.setBackground(new java.awt.Color(25, 55, 113));
        txtId.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        txtId.setForeground(new java.awt.Color(204, 204, 204));
        txtId.setBorder(null);
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 112, 120, -1));

        txtCedula.setBackground(new java.awt.Color(25, 55, 113));
        txtCedula.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(204, 204, 204));
        txtCedula.setBorder(null);
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        jPanel2.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 172, 193, -1));

        txtNombre.setBackground(new java.awt.Color(25, 55, 113));
        txtNombre.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtNombre.setBorder(null);
        txtNombre.setVerifyInputWhenFocusTarget(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 230, 193, -1));

        txtApellido.setBackground(new java.awt.Color(25, 55, 113));
        txtApellido.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(204, 204, 204));
        txtApellido.setBorder(null);
        jPanel2.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 289, 193, -1));

        txtDireccion.setBackground(new java.awt.Color(25, 55, 113));
        txtDireccion.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(204, 204, 204));
        txtDireccion.setBorder(null);
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 349, 193, -1));

        txtEmail.setBackground(new java.awt.Color(25, 55, 113));
        txtEmail.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(204, 204, 204));
        txtEmail.setBorder(null);
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 112, 220, -1));

        cbxSexo.setBackground(new java.awt.Color(25, 55, 113));
        cbxSexo.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        cbxSexo.setForeground(new java.awt.Color(204, 204, 204));
        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Masculino", "Femenino" }));
        cbxSexo.setBorder(null);
        cbxSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSexoActionPerformed(evt);
            }
        });
        jPanel2.add(cbxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 345, 210, -1));

        txtFecha.setBackground(new java.awt.Color(25, 55, 113));
        txtFecha.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(204, 204, 204));
        txtFecha.setBorder(null);
        jPanel2.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 172, 220, -1));

        txtDiscapacidad.setBackground(new java.awt.Color(25, 55, 113));
        txtDiscapacidad.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        txtDiscapacidad.setForeground(new java.awt.Color(204, 204, 204));
        txtDiscapacidad.setBorder(null);
        jPanel2.add(txtDiscapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 234, 160, -1));

        txtObersevaciones.setBackground(new java.awt.Color(25, 55, 113));
        txtObersevaciones.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        txtObersevaciones.setForeground(new java.awt.Color(204, 204, 204));
        txtObersevaciones.setBorder(null);
        jPanel2.add(txtObersevaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 289, 160, -1));

        btn_LIMPIAR.setBackground(new java.awt.Color(37, 67, 117));
        btn_LIMPIAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_LIMPIAR.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_LIMPIARMouseMoved(evt);
            }
        });
        btn_LIMPIAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LIMPIARMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_LIMPIARMouseExited(evt);
            }
        });
        btn_LIMPIAR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Limpiar");
        btn_LIMPIAR.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 7, 80, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/limpiar.png"))); // NOI18N
        btn_LIMPIAR.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 0, -1, 40));

        jPanel2.add(btn_LIMPIAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 130, 40));

        btn__ELIMINAR.setBackground(new java.awt.Color(37, 67, 117));
        btn__ELIMINAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn__ELIMINAR.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn__ELIMINARMouseMoved(evt);
            }
        });
        btn__ELIMINAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn__ELIMINARMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn__ELIMINARMouseExited(evt);
            }
        });
        btn__ELIMINAR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Eliminar");
        btn__ELIMINAR.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 7, 80, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tacho2.png"))); // NOI18N
        btn__ELIMINAR.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 0, -1, 40));

        jPanel2.add(btn__ELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 130, 40));

        btn_MODIFICAR.setBackground(new java.awt.Color(37, 67, 117));
        btn_MODIFICAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_MODIFICAR.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_MODIFICARMouseMoved(evt);
            }
        });
        btn_MODIFICAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_MODIFICARMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_MODIFICARMouseExited(evt);
            }
        });
        btn_MODIFICAR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Modificar");
        btn_MODIFICAR.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 7, 80, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modificar2.png"))); // NOI18N
        btn_MODIFICAR.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1, -1, 40));

        jPanel2.add(btn_MODIFICAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 130, 40));

        btn_GUARDAR.setBackground(new java.awt.Color(37, 67, 117));
        btn_GUARDAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_GUARDAR.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_GUARDARMouseMoved(evt);
            }
        });
        btn_GUARDAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_GUARDARMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_GUARDARMouseExited(evt);
            }
        });
        btn_GUARDAR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Guardar");
        btn_GUARDAR.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 7, 80, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guardar2.png"))); // NOI18N
        btn_GUARDAR.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, 40));

        jPanel2.add(btn_GUARDAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 130, 40));

        jlb_relleno3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RELLENO5.jpeg"))); // NOI18N
        jPanel2.add(jlb_relleno3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 11, 820, 500));

        Menu.addTab("Ingresar Alumnos", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblAlumno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cedula", "Apellido", "Nombre", "Direccion", "Email", "Fecha Nac.", "Discapacidad", "Observaciones", "Genero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlumnoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAlumno);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 740, 370));

        btn_ELIMINAR2.setBackground(new java.awt.Color(37, 67, 117));
        btn_ELIMINAR2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ELIMINAR2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_ELIMINAR2MouseMoved(evt);
            }
        });
        btn_ELIMINAR2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ELIMINAR2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ELIMINAR2MouseExited(evt);
            }
        });
        btn_ELIMINAR2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Bahnschrift", 0, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("  Eliminar");
        btn_ELIMINAR2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 8, -1, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tacho2.png"))); // NOI18N
        btn_ELIMINAR2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 50));

        jPanel3.add(btn_ELIMINAR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 210, 50));

        jlb_relleno1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RELLENO1.jpeg"))); // NOI18N
        jPanel3.add(jlb_relleno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 820, 520));

        Menu.addTab("Tabla", jPanel3);

        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 780, 540));

        jlb_relleno2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RELLENO1.jpeg"))); // NOI18N
        getContentPane().add(jlb_relleno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 830, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSexoActionPerformed

    private void tblAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlumnoMouseClicked

                try {
            int fila = tblAlumno.getSelectedRow();
            String id = tblAlumno.getValueAt(fila, 0).toString();

            PreparedStatement ps;
            ResultSet rs;

            Connection conectar = Cconexion.estblecerConexion();
            ps = conectar.prepareStatement("SELECT * FROM v_alumno_consulta WHERE codigo_alu = ?");
            ps.setString(1, id);
            rs = ps.executeQuery();

            while (rs.next()) {
                txtId.setText(String.valueOf(id));
                txtCedula.setText(rs.getString("cedula_alu").trim());
                txtApellido.setText(rs.getString("apellido_alu").trim());
                txtNombre.setText(rs.getString("nombre_alu").trim());
                txtDireccion.setText(rs.getString("direccion_alu").trim());
                txtEmail.setText(rs.getString("email_alu").trim());
                txtFecha.setText(rs.getString("date_alu").trim());
                txtDiscapacidad.setText(rs.getString("discapacidad").trim());
                txtObersevaciones.setText(rs.getString("oberservaciones_alu").trim());
                cbxSexo.setSelectedItem(rs.getString("sexo_alu").trim());
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_tblAlumnoMouseClicked

    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
        Menu.setSelectedIndex(0);
    }//GEN-LAST:event_btn1MouseClicked

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
        Menu.setSelectedIndex(1);
    }//GEN-LAST:event_btn2MouseClicked

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn3MouseClicked

    private void btn_ELIMINAR2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ELIMINAR2MouseClicked
        String id = txtId.getText();
        
        Connection conectar = Cconexion.estblecerConexion();

        try
        {

            PreparedStatement ps = conectar.prepareStatement("exec sp_delete_alu ?");
            ps.setString(1, txtId.getText());

            int res = ps.executeUpdate();

            if (res > 0)
            {
                JOptionPane.showMessageDialog(null, "Registro Eliminado");
                limpiar();
                cargartabla();
            } else
            {
                JOptionPane.showMessageDialog(null, "Error al guardar registro");
                limpiar();
                cargartabla();
            }
            conectar.close();
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btn_ELIMINAR2MouseClicked

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btn1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseMoved
        btn1.setBackground(new Color(108,149,196));
    }//GEN-LAST:event_btn1MouseMoved

    private void btn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseExited
        btn1.setBackground(new Color(35,63,111));
    }//GEN-LAST:event_btn1MouseExited

    private void btn2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseMoved
        btn2.setBackground(new Color(108,149,196));
    }//GEN-LAST:event_btn2MouseMoved

    private void btn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseExited
        btn2.setBackground(new Color(35,63,111));
    }//GEN-LAST:event_btn2MouseExited

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void btn3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseMoved
        btn3.setBackground(new Color(108,149,196));
    }//GEN-LAST:event_btn3MouseMoved

    private void btn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseExited
        btn3.setBackground(new Color(35,63,111));
    }//GEN-LAST:event_btn3MouseExited

    private void btn_BUSCARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BUSCARMouseClicked
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;

        try
        {
            Connection conectar = Cconexion.estblecerConexion();
            ps = conectar.prepareStatement("exec sp_buscar_alu ?");
            ps.setString(1, txtId.getText());
            rs = ps.executeQuery();

            if (rs.next())
            {
                txtId.setText(rs.getString("codigo_alu"));
                txtCedula.setText(rs.getString("cedula_alu"));
                txtApellido.setText(rs.getString("apellido_alu"));
                txtNombre.setText(rs.getString("nombre_alu"));
                txtDireccion.setText(rs.getString("direccion_alu"));
                txtEmail.setText(rs.getString("email_alu"));
                txtFecha.setText(rs.getString("date_alu"));
                txtDiscapacidad.setText(rs.getString("discapacidad"));
                txtObersevaciones.setText(rs.getString("oberservaciones_alu"));
                cbxSexo.setSelectedItem(rs.getString("sexo_alu"));
            }

        } catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btn_BUSCARMouseClicked

    private void btn_GUARDARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_GUARDARMouseClicked
        Connection conectar = Cconexion.estblecerConexion();

        try
        {

            PreparedStatement ps = conectar.prepareStatement("exec sp_ingresar_cv ?,?,?,?,?,?,?,?,?,?");
            ps.setString(1, txtId.getText());
            ps.setString(2, txtCedula.getText());
            ps.setString(3, txtApellido.getText());
            ps.setString(4, txtNombre.getText());
            ps.setString(5, txtDireccion.getText());
            ps.setString(6, txtEmail.getText());
            ps.setDate(7, java.sql.Date.valueOf(txtFecha.getText()));
            ps.setString(8, txtDiscapacidad.getText());
            ps.setString(9, txtObersevaciones.getText());
            ps.setString(10, cbxSexo.getSelectedItem().toString());

            int res = ps.executeUpdate();

            if (res > 0)
            {
                JOptionPane.showMessageDialog(null, "Registro Guardado");
                limpiar();
                cargartabla();
            } else
            {
                JOptionPane.showMessageDialog(null, "Error al guardar registro");
                limpiar();
                cargartabla();
            }
            conectar.close();
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btn_GUARDARMouseClicked

    private void btn_MODIFICARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MODIFICARMouseClicked
        String id = txtId.getText();
        
        Connection conectar = Cconexion.estblecerConexion();

        try
        {

            PreparedStatement ps = conectar.prepareStatement("exec sp_modificar_alu ?,?,?,?,?,?,?,?,?,?");
            ps.setString(1, txtId.getText());
            ps.setString(2, txtCedula.getText());
            ps.setString(3, txtApellido.getText());
            ps.setString(4, txtNombre.getText());
            ps.setString(5, txtDireccion.getText());
            ps.setString(6, txtEmail.getText());
            ps.setDate(7, java.sql.Date.valueOf(txtFecha.getText()));
            ps.setString(8, txtDiscapacidad.getText());
            ps.setString(9, txtObersevaciones.getText());
            ps.setString(10, cbxSexo.getSelectedItem().toString());

            int res = ps.executeUpdate();

            if (res > 0)
            {
                JOptionPane.showMessageDialog(null, "Registro Modfificado");
                limpiar();
                cargartabla();
            } else
            {
                JOptionPane.showMessageDialog(null, "Error al guardar registro");
                limpiar();
                cargartabla();
            }
            conectar.close();
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btn_MODIFICARMouseClicked

    private void btn__ELIMINARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn__ELIMINARMouseClicked
        String id = txtId.getText();
        
        Connection conectar = Cconexion.estblecerConexion();

        try
        {

            PreparedStatement ps = conectar.prepareStatement("exec sp_delete_alu ?");
            ps.setString(1, txtId.getText());

            int res = ps.executeUpdate();

            if (res > 0)
            {
                JOptionPane.showMessageDialog(null, "Registro Eliminado");
                limpiar();
                cargartabla();
            } else
            {
                JOptionPane.showMessageDialog(null, "Error al guardar registro");
                limpiar();
                cargartabla();
            }
            conectar.close();
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btn__ELIMINARMouseClicked

    private void btn_LIMPIARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LIMPIARMouseClicked
        limpiar();
    }//GEN-LAST:event_btn_LIMPIARMouseClicked

    private void btn_GUARDARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_GUARDARMouseExited
        btn_GUARDAR.setBackground(new Color(37,67,117));
    }//GEN-LAST:event_btn_GUARDARMouseExited

    private void btn_GUARDARMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_GUARDARMouseMoved
        btn_GUARDAR.setBackground(new Color(0,176,80));
        
    }//GEN-LAST:event_btn_GUARDARMouseMoved

    private void btn_MODIFICARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MODIFICARMouseExited
        btn_MODIFICAR.setBackground(new Color(37,67,117));
    }//GEN-LAST:event_btn_MODIFICARMouseExited

    private void btn_MODIFICARMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MODIFICARMouseMoved
         btn_MODIFICAR.setBackground(new Color(108,149,196));
    }//GEN-LAST:event_btn_MODIFICARMouseMoved

    private void btn__ELIMINARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn__ELIMINARMouseExited
        btn__ELIMINAR.setBackground(new Color(37,67,117));
    }//GEN-LAST:event_btn__ELIMINARMouseExited

    private void btn__ELIMINARMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn__ELIMINARMouseMoved
       btn__ELIMINAR.setBackground(new Color(192,0,0));
    }//GEN-LAST:event_btn__ELIMINARMouseMoved

    private void btn_LIMPIARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LIMPIARMouseExited
        btn_LIMPIAR.setBackground(new Color(37,67,117));
    }//GEN-LAST:event_btn_LIMPIARMouseExited

    private void btn_LIMPIARMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LIMPIARMouseMoved
        btn_LIMPIAR.setBackground(new Color(108,149,196));
    }//GEN-LAST:event_btn_LIMPIARMouseMoved

    private void btn_ELIMINAR2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ELIMINAR2MouseExited
        btn_ELIMINAR2.setBackground(new Color(37,67,117));
    }//GEN-LAST:event_btn_ELIMINAR2MouseExited

    private void btn_ELIMINAR2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ELIMINAR2MouseMoved
         btn_ELIMINAR2.setBackground(new Color(192,0,0));
    }//GEN-LAST:event_btn_ELIMINAR2MouseMoved

    private void btn_BUSCARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BUSCARMouseExited
        btn_BUSCAR.setBackground(new Color(35,63,111));
    }//GEN-LAST:event_btn_BUSCARMouseExited

    private void btn_BUSCARMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BUSCARMouseMoved
        btn_BUSCAR.setBackground(new Color(108,149,196));
    }//GEN-LAST:event_btn_BUSCARMouseMoved

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String selectedItem = (String) jComboBox1.getSelectedItem();
        if (selectedItem.equals("Ingresar / Buscar")) {
            Menu.setSelectedIndex(0);
        } else if (selectedItem.equals("Vizualizar")) {
            Menu.setSelectedIndex(1);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void cargartabla() {
        DefaultTableModel modeloTabla = (DefaultTableModel) tblAlumno.getModel();
        modeloTabla.setRowCount(0);

        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;

        int columnas;

        try
        {
            Connection conectar = Cconexion.estblecerConexion();
            ps = conectar.prepareStatement("exec sp_seleccion_alu");
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();

            while (rs.next())
            {
                Object[] fila = new Object[columnas];
                for (int indice = 0; indice < columnas; indice++)
                {
                    fila[indice] = rs.getObject(indice + 1);
                }
                modeloTabla.addRow(fila);
            }

        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Motif".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Menu;
    private javax.swing.JPanel btn1;
    private javax.swing.JPanel btn2;
    private javax.swing.JPanel btn3;
    private javax.swing.JPanel btn_BUSCAR;
    private javax.swing.JPanel btn_ELIMINAR2;
    private javax.swing.JPanel btn_GUARDAR;
    private javax.swing.JPanel btn_LIMPIAR;
    private javax.swing.JPanel btn_MODIFICAR;
    private javax.swing.JPanel btn__ELIMINAR;
    private javax.swing.JComboBox<String> cbxSexo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlb_encabezado1;
    private javax.swing.JLabel jlb_relleno1;
    private javax.swing.JLabel jlb_relleno2;
    private javax.swing.JLabel jlb_relleno3;
    private javax.swing.JPanel panel_btn;
    public javax.swing.JTable tblAlumno;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDiscapacidad;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtObersevaciones;
    // End of variables declaration//GEN-END:variables
}
