/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import escolast_bdd_4to.bdd_escolast.Cconexion;
import java.awt.Color;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        
        txtUsuario.setBackground(new java.awt.Color(0,0,0,1));
        txtContrasenia.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtContrasenia = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        btb_ACCEDER = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btb_SALIR = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAccederUsuario = new javax.swing.JButton();
        lbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtContrasenia.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        txtContrasenia.setForeground(new java.awt.Color(204, 204, 204));
        txtContrasenia.setBorder(null);
        txtContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseniaActionPerformed(evt);
            }
        });
        getContentPane().add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 356, 330, 30));

        txtUsuario.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setBorder(null);
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 330, 30));

        btb_ACCEDER.setBackground(new java.awt.Color(72, 137, 173));
        btb_ACCEDER.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btb_ACCEDER.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btb_ACCEDERMouseMoved(evt);
            }
        });
        btb_ACCEDER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btb_ACCEDERMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btb_ACCEDERMouseExited(evt);
            }
        });
        btb_ACCEDER.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("        ACCEDER");
        btb_ACCEDER.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 50));

        getContentPane().add(btb_ACCEDER, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 190, 50));

        btb_SALIR.setBackground(new java.awt.Color(72, 137, 173));
        btb_SALIR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btb_SALIR.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btb_SALIRMouseMoved(evt);
            }
        });
        btb_SALIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btb_SALIRMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btb_SALIRMouseExited(evt);
            }
        });
        btb_SALIR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("           SALIR");
        btb_SALIR.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 50));

        getContentPane().add(btb_SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 190, 50));

        btnAccederUsuario.setText("Acceder");
        btnAccederUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnAccederUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login-1.jpeg"))); // NOI18N
        getContentPane().add(lbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btb_ACCEDERMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btb_ACCEDERMouseMoved
        btb_ACCEDER.setBackground(new Color(36,83,115));
    }//GEN-LAST:event_btb_ACCEDERMouseMoved

    private void btb_ACCEDERMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btb_ACCEDERMouseExited
        btb_ACCEDER.setBackground(new Color(72,137,173));
    }//GEN-LAST:event_btb_ACCEDERMouseExited

    private void btb_SALIRMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btb_SALIRMouseMoved
        btb_SALIR.setBackground(new Color(36,83,115));
    }//GEN-LAST:event_btb_SALIRMouseMoved

    private void btb_SALIRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btb_SALIRMouseExited
        btb_SALIR.setBackground(new Color(72,137,173));
    }//GEN-LAST:event_btb_SALIRMouseExited

    private void btb_ACCEDERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btb_ACCEDERMouseClicked
               
        this.setVisible(false);
    }//GEN-LAST:event_btb_ACCEDERMouseClicked

    private void btb_SALIRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btb_SALIRMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btb_SALIRMouseClicked

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseniaActionPerformed

    private void btnAccederUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederUsuarioActionPerformed
        String codigoUsu = txtUsuario.getText();
        String contraseniaUsu = new String(txtContrasenia.getPassword());

        try {
            Connection conectar = Cconexion.estblecerConexion(); // Obtén la conexión a la base de datos

            String sql = "sp_login_usu(?, ?) }";
            CallableStatement statement = conectar.prepareCall(sql);

            statement.setString(1, codigoUsu);
            statement.setString(2, contraseniaUsu);

            boolean hasResults = statement.execute();

            if (hasResults) {
                // Puede haber varios conjuntos de resultados, pero asumamos uno
                while (statement.getResultSet().next()) {
                    String mensaje = statement.getResultSet().getString("Mensaje");
                    if (mensaje.equals("Acceso concedido")) {
                        // Acceso concedido, realiza las acciones necesarias
                        // por ejemplo, abre una nueva ventana o realiza alguna operación
                        JOptionPane.showMessageDialog(this, "Acceso concedido");
                    } else {
                        // Acceso denegado, muestra un mensaje de error
                        JOptionPane.showMessageDialog(this, "Acceso denegado");
                    }
                }
            }

            statement.close();
            conectar.close();

        } catch (SQLException e) {
            e.printStackTrace();
            // Manejo de excepciones
        }
    }//GEN-LAST:event_btnAccederUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btb_ACCEDER;
    private javax.swing.JPanel btb_SALIR;
    private javax.swing.JButton btnAccederUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
